//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dsw_cineEntities : DbContext
    {
        public dsw_cineEntities()
            : base("name=dsw_cineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_clientes> tb_clientes { get; set; }
        public virtual DbSet<tb_funciones> tb_funciones { get; set; }
        public virtual DbSet<tb_locales> tb_locales { get; set; }
        public virtual DbSet<tb_peliculas> tb_peliculas { get; set; }
        public virtual DbSet<tb_reservas> tb_reservas { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int sp_actualizarCliente(string dni, string nom, string correo, string telf_f, string telf_c)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telf_fParameter = telf_f != null ?
                new ObjectParameter("telf_f", telf_f) :
                new ObjectParameter("telf_f", typeof(string));
    
            var telf_cParameter = telf_c != null ?
                new ObjectParameter("telf_c", telf_c) :
                new ObjectParameter("telf_c", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizarCliente", dniParameter, nomParameter, correoParameter, telf_fParameter, telf_cParameter);
        }
    
        public virtual ObjectResult<sp_buscarCliente_Result> sp_buscarCliente(Nullable<int> dni)
        {
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_buscarCliente_Result>("sp_buscarCliente", dniParameter);
        }
    
        public virtual ObjectResult<sp_consultarReserva_Result> sp_consultarReserva(Nullable<int> nro)
        {
            var nroParameter = nro.HasValue ?
                new ObjectParameter("nro", nro) :
                new ObjectParameter("nro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultarReserva_Result>("sp_consultarReserva", nroParameter);
        }
    
        public virtual int sp_registrarCliente(string dni, string nom, string correo, string telf_f, string telf_c)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telf_fParameter = telf_f != null ?
                new ObjectParameter("telf_f", telf_f) :
                new ObjectParameter("telf_f", typeof(string));
    
            var telf_cParameter = telf_c != null ?
                new ObjectParameter("telf_c", telf_c) :
                new ObjectParameter("telf_c", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_registrarCliente", dniParameter, nomParameter, correoParameter, telf_fParameter, telf_cParameter);
        }
    
        public virtual ObjectResult<sp_listarPeliculas_Result> sp_listarPeliculas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarPeliculas_Result>("sp_listarPeliculas");
        }
    
        public virtual ObjectResult<sp_ListaFunciones_Result> sp_ListaFunciones(Nullable<System.DateTime> fecha, string local)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var localParameter = local != null ?
                new ObjectParameter("local", local) :
                new ObjectParameter("local", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaFunciones_Result>("sp_ListaFunciones", fechaParameter, localParameter);
        }
    
        public virtual ObjectResult<sp_listaLocales_Result> sp_listaLocales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listaLocales_Result>("sp_listaLocales");
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sp_ListarFechas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sp_ListarFechas");
        }
    
        public virtual int sp_Reservar(Nullable<int> funcion, string dni)
        {
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("Funcion", funcion) :
                new ObjectParameter("Funcion", typeof(int));
    
            var dniParameter = dni != null ?
                new ObjectParameter("Dni", dni) :
                new ObjectParameter("Dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Reservar", funcionParameter, dniParameter);
        }
    }
}
