//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_clientes()
        {
            this.tb_reservas = new HashSet<tb_reservas>();
        }
    
        public string dni { get; set; }
        public string nom_cliente { get; set; }
        public string correo_cliente { get; set; }
        public string telefono_fijo { get; set; }
        public string telefono_celular { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reservas> tb_reservas { get; set; }
    }
}
