//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_funciones()
        {
            this.tb_reservas = new HashSet<tb_reservas>();
        }
    
        public int id_funcion { get; set; }
        public Nullable<int> num_sala { get; set; }
        public Nullable<System.DateTime> um_fecha { get; set; }
        public string inicio { get; set; }
        public string fin { get; set; }
        public Nullable<int> id_pelicula { get; set; }
        public Nullable<int> id_local { get; set; }
    
        public virtual tb_locales tb_locales { get; set; }
        public virtual tb_peliculas tb_peliculas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reservas> tb_reservas { get; set; }
    }
}
