//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reservas
    {
        public int id_reserva { get; set; }
        public Nullable<int> id_funcion { get; set; }
        public string dni { get; set; }
    
        public virtual tb_clientes tb_clientes { get; set; }
        public virtual tb_funciones tb_funciones { get; set; }
    }
}
